/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    HsMusic: typeof import('./src/components/hsMusic/index.vue')['default']
    'Index备份': typeof import('./src/components/hsMusic/index备份.vue')['default']
    MusicActive: typeof import('./src/components/hsMusic/musicActive/index.vue')['default']
    MusicLyric: typeof import('./src/components/hsMusic/musicLyric/index.vue')['default']
    MusicPanel: typeof import('./src/components/hsMusic/musicPanel/index.vue')['default']
    MusicProgress: typeof import('./src/components/hsMusic/musicProgress/index.vue')['default']
    RotateCube: typeof import('./src/components/hsMusic/RotateCube/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
